language: java

jdk:
  - oraclejdk7

matrix:
  fast_finish: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: "mvn clean install"

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/56a42f65b462c237bbe9
    on_success: change
    on_failure: always
    on_start: false
