language: java

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: 
  - "mvn clean install"
  - "java -jar /home/travis/build/Javauto/javauto-core/target/javauto-1.1.0.jar /home/travis/build/Javauto/javauto-core/src/test/resources/script/tests.javauto"
  - "java -jar tests.jar"

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/56a42f65b462c237bbe9
    on_success: change
    on_failure: always
    on_start: false
